---
- name: "Automate Creation of Project in  OSP"
  hosts: localhost
  vars:
    cloud: local
    domain: default
    project_name: automated
    project_description: "ansible managed project"
    username: ansible_user
    userpsk: ansible_password
    emailadd: ansible@mdi.net.ph
    role1: admin
    role2: _member_
    external_network: public
    router_name: router_public_private
    internal_network: private
    external_subnet: public_subnet
    internal_subnet: private_subnet
    cidr_int: "192.168.0.0/24"
    extip: 192.168.80.251
    dns1_int: 8.8.8.8
    dns2_int: 8.8.4.4


  tasks:
  - name: Verify Authentication
    include_tasks: openstack/verify_authentication.yaml
    vars:
      cn: "{{ cloud }}"

  - name: Create project {{ project_name }}
    include_tasks: openstack/create_project.yaml
    vars:
      pn: "{{ project_name }}"
      cn: "{{ cloud }}"
      dom: "{{ domain }}"
      desc: "{{ project_description }}"

  - name: Create user {{ username }}
    include_tasks: openstack/create_user.yaml 
    vars:
      cn: "{{ cloud }}"
      dom: "{{ domain }}"
      un: "{{ username }}"
      pwd: "{{ userpsk }}"
      pn: "{{ project_name }}"
      email: "{{ emailadd }}"

  - name: Grant {{ role1 }} to user {{ username }} in {{ project_name }}
    include_tasks: openstack/grant_user.yaml
    vars:
      cn: "{{ cloud }}"
      un: "{{ username }}"
      role: "{{ role1 }}"
      pn: "{{ project_name }}"

  - name: Grant {{ role2 }} to user {{ username }} in admin
    include_tasks: openstack/grant_user.yaml
    vars:
      cn: "{{ cloud }}"
      un: "{{ username }}"
      role: "{{ role2 }}"
      pn: admin

  - name: Create network "{{ internal_network }}"
    include_tasks: openstack/create_network.yaml
    vars:
      cn: "{{ cloud }}"
      nn: "{{ internal_network }}"
      pn: "{{ project_name }}"

  - name: Create subnet "{{ internal_subnet }}"
    include_tasks: openstack/create_subnet.yaml
    vars:
      nn: "{{ internal_network }}"
      cn: "{{ cloud }}"
      sn: "{{ internal_subnet }}"
      cidr: "{{ cidr_int }}"
      dns1: "{{ dns1_int }}"
      dns2: "{{ dns2_int }}"

  - name: Create router {{ router_name }}
    include_tasks: openstack/create_router.yaml
    vars:
      cn: "{{ cloud }}"
      rn: "{{ router_name }}"
      extnn: "{{ external_network }}"
      extsn: "{{ external_subnet }}"
      ext_ip: "{{ extip }}"
      intsn: "{{ internal_subnet }}"


